namespace: vexxhost
name: flux
version: 0.1.3
readme: README.md
authors:
  - Mohammed Naser <mnaser@vexxhost.com>
description: Ansible collection for managing Flux CD
license:
  - Apache-2.0
dependencies:
  vexxhost.containers: '>=1.3.0'
tags:
  - application
  - cloud
  - infrastructure
  - linux
repository: https://github.com/vexxhost/ansible-collection-flux
documentation: https://github.com/vexxhost/ansible-collection-flux/tree/main/docs
homepage: https://github.com/vexxhost/ansible-collection-flux
issues: https://github.com/vexxhost/ansible-collection-flux/issues
build_ignore:
  - .github
