# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- name: Get current HelmRelease
  run_once: true
  kubernetes.core.k8s_info:
    api_version: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    name: "{{ metrics_server_helm_release_name }}"
    namespace: "{{ metrics_server_helm_release_namespace }}"
  register: metrics_server_helm_release_current

- name: Install "metrics-server"
  run_once: true
  kubernetes.core.k8s:
    server_side_apply:
      field_manager: "atmosphere.common"
      force_conflicts: true
    definition:
      - apiVersion: v1
        kind: Namespace
        metadata:
          name: "{{ metrics_server_helm_release_namespace }}"

      - apiVersion: source.toolkit.fluxcd.io/v1
        kind: HelmRepository
        metadata:
          name: "{{ metrics_server_helm_repository_name }}"
          namespace: "{{ metrics_server_helm_release_namespace }}"
        spec:
          interval: 60m
          url: "{{ metrics_server_helm_repository_url }}"

      - apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: "{{ metrics_server_helm_release_name }}"
          namespace: "{{ metrics_server_helm_release_namespace }}"
        spec:
          interval: 10m
          releaseName: "{{ metrics_server_helm_release_name }}"
          chart:
            spec:
              chart: "{{ metrics_server_helm_chart_name }}"
              version: "{{ metrics_server_helm_chart_version }}"
              sourceRef:
                kind: HelmRepository
                name: "{{ metrics_server_helm_repository_name }}"
          values: >-
            {{
              metrics_server_helm_release_current.resources[0]['spec']['values'] | default({})
              | atmosphere.common.nullify_missing_values(metrics_server_helm_values)
              | atmosphere.common.merge_replace_nulls(_metrics_server_helm_values)
            }}
