# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

_download_artifact_goarch_groups:
  x86_64: amd64
  aarch64: arm64
  armv7l: arm

download_artifact_goarch: >-
  {%- if ansible_facts['architecture'] in _download_artifact_goarch_groups -%}
  {{ _download_artifact_goarch_groups[ansible_facts['architecture']] }}
  {%- else -%}
  {{ ansible_facts['architecture'] }}
  {%- endif -%}
