- name: Gather network interface facts
  ansible.builtin.setup:
    gather_subset:
      - network
  when: ansible_default_ipv4 is not defined

- name: Install Ironic Standalone
  run_once: true
  kubernetes.core.k8s:
    server_side_apply:
      field_manager: "atmosphere.common"
      force_conflicts: true
    definition:
      - apiVersion: v1
        kind: Namespace
        metadata:
          name: "{{ ironic_standalone_namespace }}"

      - apiVersion: ironic.metal3.io/v1alpha1
        kind: Ironic
        metadata:
          name: "{{ ironic_standalone_name }}"
          namespace: "{{ ironic_standalone_namespace }}"
        spec:
          networking:
            interface: "{{ ironic_standalone_interface }}"
            ipAddress: "{{ ironic_standalone_ip_address }}"
            dhcp:
              networkCIDR: "{{ ironic_standalone_dhcp_cidr }}"
              rangeBegin: "{{ ironic_standalone_dhcp_range_start }}"
              rangeEnd: "{{ ironic_standalone_dhcp_range_end }}"
              serveDNS: true
