# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- name: Deploy "cert-manager"
  hosts: "{{ target | default('all') }}"
  gather_facts: false
  roles:
    - role: atmosphere.common.cert_manager
      tags:
        - cert-manager
