# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- name: Bootstrap Flux CD
  hosts: "{{ target | default('all') }}"
  roles:
    - role: atmosphere.common.flux
      tags:
        - flux
