# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- name: Get current HelmRelease
  run_once: true
  kubernetes.core.k8s_info:
    api_version: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    name: "{{ cert_manager_helm_release_name }}"
    namespace: "{{ cert_manager_helm_release_namespace }}"
  register: cert_manager_helm_release_current

- name: Install "cert-manager"
  run_once: true
  kubernetes.core.k8s:
    server_side_apply:
      field_manager: "atmosphere.common"
      force_conflicts: true
    definition:
      - apiVersion: v1
        kind: Namespace
        metadata:
          name: "{{ cert_manager_helm_release_namespace }}"

      - apiVersion: source.toolkit.fluxcd.io/v1
        kind: HelmRepository
        metadata:
          name: "{{ cert_manager_helm_repository_name }}"
          namespace: "{{ cert_manager_helm_release_namespace }}"
        spec:
          interval: 5m
          url: "{{ cert_manager_helm_repository_url }}"

      - apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: "{{ cert_manager_helm_release_name }}"
          namespace: "{{ cert_manager_helm_release_namespace }}"
        spec:
          interval: 10m
          releaseName: "{{ cert_manager_helm_release_name }}"
          chart:
            spec:
              chart: "{{ cert_manager_helm_chart_name }}"
              version: "{{ cert_manager_helm_chart_version }}"
              sourceRef:
                kind: HelmRepository
                name: "{{ cert_manager_helm_repository_name }}"
          values: >-
            {{
              cert_manager_helm_release_current.resources[0]['spec']['values'] | default({})
              | atmosphere.common.nullify_missing_values(cert_manager_helm_values)
              | atmosphere.common.merge_replace_nulls(_cert_manager_helm_values)
            }}
