# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- name: Install "cert-manager"
  run_once: true
  kubernetes.core.k8s:
    server_side_apply:
      field_manager: "atmosphere.common"
      force_conflicts: true
    definition:
      - apiVersion: v1
        kind: Namespace
        metadata:
          name: "{{ cert_manager_helm_release_namespace }}"

      - apiVersion: source.toolkit.fluxcd.io/v1
        kind: HelmRepository
        metadata:
          name: "{{ cert_manager_helm_repository_name }}"
          namespace: "{{ cert_manager_helm_release_namespace }}"
        spec:
          interval: 5m
          url: "{{ cert_manager_helm_repository_url }}"

      - apiVersion: v1
        kind: Secret
        metadata:
          name: "{{ cert_manager_helm_release_secret_name }}"
          namespace: "{{ cert_manager_helm_release_namespace }}"
        type: Opaque
        stringData:
          values.yaml: "{{ lookup('atmosphere.common.helm_values', 'cert_manager') }}"

      - apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: "{{ cert_manager_helm_release_name }}"
          namespace: "{{ cert_manager_helm_release_namespace }}"
          annotations:
            reconcile.fluxcd.io/requestedAt: "{{ lookup('atmosphere.common.helm_values', 'cert_manager') | checksum }}"
        spec:
          interval: 10m
          releaseName: "{{ cert_manager_helm_release_name }}"
          chart:
            spec:
              chart: "{{ cert_manager_helm_chart_name }}"
              version: "{{ cert_manager_helm_chart_version }}"
              sourceRef:
                kind: HelmRepository
                name: "{{ cert_manager_helm_repository_name }}"
          valuesFrom:
            - kind: Secret
              name: "{{ cert_manager_helm_release_secret_name }}"
