name: ci

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  flux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
      - uses: astral-sh/setup-uv@c7f87aa956e4c323abf06d5dec078e358f6b4d04 # v6.0.0
      - run: uv run ansible-galaxy collection install ${{ github.workspace }}
      - run: |
          uv run ansible-playbook \
            --connection=local \
            --extra-vars target=localhost \
              atmosphere.common.flux
      - run: |
          kubectl wait \
            --namespace flux-system \
            --for=condition=available \
            --timeout=5m \
            deployment/helm-controller \
            deployment/kustomize-controller \
            deployment/notification-controller \
            deployment/source-controller

  cert-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
      - uses: astral-sh/setup-uv@c7f87aa956e4c323abf06d5dec078e358f6b4d04 # v6.0.0
      - run: uv run ansible-galaxy collection install ${{ github.workspace }}
      - run: |
          uv run ansible-playbook \
            --connection=local \
            --extra-vars target=localhost \
              atmosphere.common.flux \
              atmosphere.common.cert_manager
      - run: |
          kubectl wait \
            --namespace cert-manager \
            --for=condition=ready \
            --timeout=5m \
            helmrelease/cert-manager
      - run: |
          kubectl wait \
            --namespace cert-manager \
            --for=condition=available \
            --timeout=5m \
            deployment.apps/cert-manager \
            deployment.apps/cert-manager-cainjector \
            deployment.apps/cert-manager-webhook

  metal3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
      - uses: astral-sh/setup-uv@c7f87aa956e4c323abf06d5dec078e358f6b4d04 # v6.0.0
      - run: uv run ansible-galaxy collection install ${{ github.workspace }}
      - run: |
          uv run ansible-playbook \
            --connection=local \
            --extra-vars target=localhost \
            --extra-vars ironic_standalone_ip_address=172.18.0.2 \
            --extra-vars ironic_standalone_dhcp_cidr=172.18.0.0/24 \
            --extra-vars ironic_standalone_dhcp_range_start=172.18.0.10 \
            --extra-vars ironic_standalone_dhcp_range_end=172.18.0.20 \
              atmosphere.common.flux \
              atmosphere.common.cert_manager \
              atmosphere.common.metal3
      - run: |
          kubectl wait \
            --namespace baremetal-operator-system \
            --for=condition=ready \
            --timeout=5m \
            kustomizations/baremetal-operator
      - run: |
          kubectl wait \
            --namespace ironic-standalone-operator-system \
            --for=condition=ready \
            --timeout=5m \
            kustomizations/ironic-standalone-operator
      - run: |
          kubectl wait \
            --namespace baremetal-operator-system \
            --for=condition=available \
            --timeout=5m \
            deployment.apps/baremetal-operator-controller-manager \
            deployment.apps/ironic-service
      - run: |
          kubectl wait \
            --namespace ironic-standalone-operator-system \
            --for=condition=available \
            --timeout=5m \
            deployment.apps/ironic-standalone-operator-controller-manager

  dellhw_exporter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
      - uses: astral-sh/setup-uv@0c5e2b8115b80b4c7c5ddf6ffdd634974642d182 # v5.4.1
      - run: uv run ansible-galaxy collection install ${{ github.workspace }}
      - run: |
          uv run ansible-playbook \
            --connection=local \
            --extra-vars target=localhost \
              atmosphere.common.flux \
              atmosphere.common.dellhw_exporter
      - run: |
          kubectl wait \
            --namespace monitoring \
            --for=condition=ready \
            --timeout=5m \
            helmrelease/prometheus-dellhw-exporter
      - run: |
          kubectl wait \
            --namespace monitoring \
            --for=condition=ready \
            --timeout=5m \
            pod -l app.kubernetes.io/name=prometheus-dellhw-exporter
