name: ci

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  ansible-lint:
    runs-on: depot-ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ansible/ansible-lint@v25.2.1

  bootstrap:
    runs-on: depot-ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: helm/kind-action@v1
      - run: ansible-galaxy collection install ${{ github.workspace }}
      - run: |
          ansible-playbook \
            --connection=local \
            --extra-vars target=localhost \
            vexxhost.flux.site

  pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: ytanikin/pr-conventional-commits@1.4.1
        with:
          task_types: '["build", "chore", "ci", "docs", "feat", "fix", "perf", "refactor", "revert", "style", "test"]'
