name: ci

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  bootstrap:
    runs-on: depot-ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: helm/kind-action@v1
      - run: ansible-galaxy collection install .
      - run: |
          ansible-playbook \
            --connection=local \
            --extra-vars target=localhost \
            vexxhost.flux.site
