name: ci

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  flux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
      - uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2
      - run: uv run ansible-galaxy collection install ${{ github.workspace }}
      - run: |
          uv run ansible-playbook \
            --connection=local \
            --extra-vars target=localhost \
              atmosphere.common.flux

  cert-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
      - uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2
      - run: uv run ansible-galaxy collection install ${{ github.workspace }}
      - run: |
          uv run ansible-playbook \
            --connection=local \
            --extra-vars target=localhost \
              atmosphere.common.flux \
              atmosphere.common.cert_manager

  metal3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
      - uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2
      - run: uv run ansible-galaxy collection install ${{ github.workspace }}
      - run: |
          uv run ansible-playbook \
            --connection=local \
            --extra-vars target=localhost \
            --extra-vars ironic_standalone_ip_address=172.18.0.2 \
            --extra-vars ironic_standalone_dhcp_cidr=172.18.0.0/24 \
            --extra-vars ironic_standalone_dhcp_range_start=172.18.0.10 \
            --extra-vars ironic_standalone_dhcp_range_end=172.18.0.20 \
              atmosphere.common.flux \
              atmosphere.common.cert_manager \
              atmosphere.common.metal3
