name: ci

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ansible/ansible-lint@c16f018b1bdfdea6717f4b5b1b141a78b86021cd # v25.2.1

  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1
      - run: ansible-galaxy collection install ${{ github.workspace }}
      - run: |
          ansible-playbook \
            --connection=local \
            --extra-vars target=localhost \
            vexxhost.flux.site
