name: ci

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ansible/ansible-lint@c16f018b1bdfdea6717f4b5b1b141a78b86021cd # v25.2.1

  flux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
      - uses: astral-sh/setup-uv@v5
      - run: uv run ansible-galaxy collection install ${{ github.workspace }}
      - run: |
          uv run ansible-playbook \
            --connection=local \
            --extra-vars target=localhost \
              atmosphere.common.flux

  cert-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
      - uses: astral-sh/setup-uv@v5
      - run: uv run ansible-galaxy collection install ${{ github.workspace }}
      - run: |
          uv run ansible-playbook \
            --connection=local \
            --extra-vars target=localhost \
              atmosphere.common.flux \
              atmosphere.common.cert_manager

  ironic-standalone-operator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
      - uses: astral-sh/setup-uv@v5
      - run: uv run ansible-galaxy collection install ${{ github.workspace }}
      - run: |
          uv run ansible-playbook \
            --connection=local \
            --extra-vars target=localhost \
              atmosphere.common.flux \
              atmosphere.common.cert_manager \
              atmosphere.common.metal3
