name: ci

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ansible/ansible-lint@v25.2.1

  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: helm/kind-action@v1
      - run: ansible-galaxy collection install ${{ github.workspace }}
      - run: |
          ansible-playbook \
            --connection=local \
            --extra-vars target=localhost \
            vexxhost.flux.site
