name: conventional-commit

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: ytanikin/pr-conventional-commits@1.4.1
        with:
          task_types: '["build", "chore", "ci", "docs", "feat", "fix", "perf", "refactor", "revert", "style", "test"]'
