name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - uses: ansible/ansible-publish-action@v1.0.0
        if: ${{ steps.release.outputs.release_created }}
        with:
          api_key: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
