# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

_dellhw_exporter_helm_values:
  image:
    repository: "{{ dellhw_exporter_image | atmosphere.common.docker_image('name') }}"
    tag: "{{ dellhw_exporter_image | atmosphere.common.docker_image('tag') }}"
